/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2021-06-03 08:00:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.project3.controller.ORSView;

public final class ErrorView404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.jpg\" sizes=\"16*16\"/>\r\n");
      out.write("<title> Error Page</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write(" \t<div align=\"center\">\r\n");
      out.write(" \t\t<img src=url(/Project03/img/image404n.jpg) width=\"550\" height=\"250\">\r\n");
      out.write(" \t\t<h1 align=\"center\" style=\"color: red\"> Ooops! Something went wrong..</h1>\r\n");
      out.write(" \t\t<font style=\"color: black ; font-size: 25px \">\r\n");
      out.write(" \t\t<b>404</b> : Requested Page not available\r\n");
      out.write(" \t\t</font>\r\n");
      out.write(" \t<div style=\"width: 25% ; text-align: justify;\">\r\n");
      out.write(" \t\t<h3 >Try :</h3>\r\n");
      out.write(" \t\t<ul>\r\n");
      out.write(" \t\t\t<li> Server under Maintain please try after Some Time </li>\r\n");
      out.write(" \t\t\t<li> Check the network cables , modem and router</li>\r\n");
      out.write(" \t\t\t<li> Reconnect to network or wi-fi Connection</li>\r\n");
      out.write(" \t\t</ul>\r\n");
      out.write(" \t</div>\r\n");
      out.write(" \t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h4 align=\"center\">\r\n");
      out.write("\t\t\t<font size=\"5px\" color=\"black\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(ORSView.WELCOME_CTL );
      out.write("\" style=\"color: silver\">*Click here to Go Back*</a>\t\t\t\r\n");
      out.write("\t\t\t</font>\r\n");
      out.write("\t\t</h4>\r\n");
      out.write("\t</form>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
